#!/bin/bash

echo "🔗 Linking to Vercel Project"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Run: vercel"
echo "2. When asked 'Set up and deploy?' → Choose 'Y'"
echo "3. Which scope? → Choose your account"
echo "4. Link to existing project? → Choose 'Y' (Yes)"
echo "5. Project name? → Enter your existing Vercel project name"
echo ""
echo "Your Vercel project name is likely one of these:"
echo "  - ai-engagement-hub"
echo "  - ai-musical-theater-course"
echo "  - staging-intelligence"
echo ""
echo "After linking, run: vercel env pull .env.development.local"
echo ""